#!/usr/bin/env python
import sys
import json
import logging
import argparse

import hgacclient

if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='HGAC Client')

  # Generate sub-parsers for each command.
  subparsers = parser.add_subparsers(help='subcommand help')
  map(lambda add: add(subparsers), hgacclient.plugin.parsers)

  # Global optional arguments.
  parser.add_argument('-d','--debug',dest='loglevel',action='store_const',
                      const=logging.DEBUG,default=logging.INFO,
                      help='Set logging level to DEBUG.')
  parser.add_argument('-u','--username',help='Authentication username.')
  parser.add_argument('-p','--password',help='Authentication password.')

  # Parse arguments.
  args = parser.parse_args()

  # Set up logging.
  logging.basicConfig(
    level = args.loglevel,
    format = '%(asctime)s %(name)-6s %(levelname)-4s %(message)s',
  )
  logging.info(args)

  # Execute the program, returning status code and a json message.
  try: status,retval = 0,args.func(**args.__dict__)
  except Exception as err: status,retval = 1,{'error': str(err)}
  else: sys.exit(status)
  finally: sys.stdout.write('%s\n' % json.dumps(retval))
